#!/bin/bash
# Squid Installer
# Author: ChefJodla
# Email: jodlaksde@gmail.com
# Github: https://github.com/ChefJodlak/GotowanieNaEkranie

read -e -p "Jak chcesz zeby sie serwery nazywaly(tylko male litery, cyfry, bez spacji)?: " name

for (( c=1; c<= 15*n; c++ ))
do  
	if [ $c -le 3 ]
	then
		yes | gcloud compute instances create $name$c --machine-type="f1-micro" --image-family="centos-6" --image-project=centos-cloud --tags=http-server,https-server --zone=europe-west1-b --metadata startup-script='#! /bin/bash

		sudo su
		yum -y update
		yum install -y squid 
		yum install httpd-tools -y
		wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/ChefJodlak/GotowanieNaEkranie/master/config.conf --no-check-certificate
		squid -z
		chkconfig squid on
		service squid start
		touch /etc/squid/squid_access; htpasswd -b /etc/squid/squid_access admin admin
		'
	elif [ $c -le 6 ]
	then
		yes | gcloud compute instances create $name$c --machine-type="f1-micro" --image-family=centos-6 --image-project=centos-cloud --tags=http-server,https-server --zone=europe-west1-c --metadata startup-script='#! /bin/bash

		sudo su
		yum -y update
		yum install -y squid 
		yum install httpd-tools -y
		wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/ChefJodlak/GotowanieNaEkranie/master/config.conf --no-check-certificate
		squid -z
		chkconfig squid on
		service squid start
		touch /etc/squid/squid_access; htpasswd -b /etc/squid/squid_access admin admin
		'
	elif [ $c -le 8 ]
	then
		yes | gcloud compute instances create $name$c --machine-type="f1-micro" --image-family=centos-6 --image-project=centos-cloud --tags=http-server,https-server --zone=europe-west1-d --metadata startup-script='#! /bin/bash

		sudo su
		yum -y update
		yum install -y squid 
		yum install httpd-tools -y
		wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/ChefJodlak/GotowanieNaEkranie/master/config.conf --no-check-certificate
		squid -z
		chkconfig squid on
		service squid start
		touch /etc/squid/squid_access; htpasswd -b /etc/squid/squid_access admin admin
		'
	elif [ $c -le 11 ]
	then
		yes | gcloud compute instances create $name$c --machine-type="f1-micro" --image-family=centos-6 --image-project=centos-cloud --tags=http-server,https-server --zone=europe-west2-a --metadata startup-script='#! /bin/bash

		sudo su
		yum -y update
		yum install -y squid 
		yum install httpd-tools -y
		wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/ChefJodlak/GotowanieNaEkranie/master/config.conf --no-check-certificate
		squid -z
		chkconfig squid on
		service squid start
		touch /etc/squid/squid_access; htpasswd -b /etc/squid/squid_access admin admin
		'
	elif [ $c -le 14 ]
	then
		yes | gcloud compute instances create $name$c --machine-type="f1-micro" --image-family=centos-6 --image-project=centos-cloud --tags=http-server,https-server --zone=europe-west2-b --metadata startup-script='#! /bin/bash

		sudo su
		yum -y update
		yum install -y squid 
		yum install httpd-tools -y
		wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/ChefJodlak/GotowanieNaEkranie/master/config.conf --no-check-certificate
		squid -z
		chkconfig squid on
		service squid start
		touch /etc/squid/squid_access; htpasswd -b /etc/squid/squid_access admin admin
		'
	elif [ $c -le 16 ]
	then
		yes | gcloud compute instances create $name$c --machine-type="f1-micro" --image-family=centos-6 --image-project=centos-cloud --tags=http-server,https-server --zone=europe-west2-c --metadata startup-script='#! /bin/bash

		sudo su
		yum -y update
		yum install -y squid 
		yum install httpd-tools -y
		wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/ChefJodlak/GotowanieNaEkranie/master/config.conf --no-check-certificate
		squid -z
		chkconfig squid on
		service squid start
		touch /etc/squid/squid_access; htpasswd -b /etc/squid/squid_access admin admin
		'
	elif [ $c -le 19 ]
	then
		yes | gcloud compute instances create $name$c --machine-type="f1-micro" --image-family=centos-6 --image-project=centos-cloud --tags=http-server,https-server --zone=europe-west3-a --metadata startup-script='#! /bin/bash

		sudo su
		yum -y update
		yum install -y squid 
		yum install httpd-tools -y
		wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/ChefJodlak/GotowanieNaEkranie/master/config.conf --no-check-certificate
		squid -z
		chkconfig squid on
		service squid start
		touch /etc/squid/squid_access; htpasswd -b /etc/squid/squid_access admin admin
		'
	elif [ $c -le 22 ]
	then
		yes | gcloud compute instances create $name$c --machine-type="f1-micro" --image-family=centos-6 --image-project=centos-cloud --tags=http-server,https-server --zone=europe-west3-b --metadata startup-script='#! /bin/bash

		sudo su
		yum -y update
		yum install -y squid 
		yum install httpd-tools -y
		wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/ChefJodlak/GotowanieNaEkranie/master/config.conf --no-check-certificate
		squid -z
		chkconfig squid on
		service squid start
		touch /etc/squid/squid_access; htpasswd -b /etc/squid/squid_access admin admin
		'
	elif [ $c -le 24 ]
	then
		yes | gcloud compute instances create $name$c --machine-type="f1-micro" --image-family=centos-6 --image-project=centos-cloud --tags=http-server,https-server --zone=europe-west3-c --metadata startup-script='#! /bin/bash

		sudo su
		yum -y update
		yum install -y squid 
		yum install httpd-tools -y
		wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/ChefJodlak/GotowanieNaEkranie/master/config.conf --no-check-certificate
		squid -z
		chkconfig squid on
		service squid start
		touch /etc/squid/squid_access; htpasswd -b /etc/squid/squid_access admin admin
		'
	elif [ $c -le 27 ]
	then
		yes | gcloud compute instances create $name$c --machine-type="f1-micro" --image-family=centos-6 --image-project=centos-cloud --tags=http-server,https-server --zone=europe-west4-a --metadata startup-script='#! /bin/bash

		sudo su
		yum -y update
		yum install -y squid 
		yum install httpd-tools -y
		wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/ChefJodlak/GotowanieNaEkranie/master/config.conf --no-check-certificate
		squid -z
		chkconfig squid on
		service squid start
		touch /etc/squid/squid_access; htpasswd -b /etc/squid/squid_access admin admin
		'
	elif [ $c -le 30 ]
	then
		yes | gcloud compute instances create $name$c --machine-type="f1-micro" --image-family=centos-6 --image-project=centos-cloud --tags=http-server,https-server --zone=europe-west4-b --metadata startup-script='#! /bin/bash

		sudo su
		yum -y update
		yum install -y squid 
		yum install httpd-tools -y
		wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/ChefJodlak/GotowanieNaEkranie/master/config.conf --no-check-certificate
		squid -z
		chkconfig squid on
		service squid start
		touch /etc/squid/squid_access; htpasswd -b /etc/squid/squid_access admin admin
		'
	elif [ $c -le 32 ]
	then
		yes | gcloud compute instances create $name$c --machine-type="f1-micro" --image-family=centos-6 --image-project=centos-cloud --tags=http-server,https-server --zone=europe-west4-c --metadata startup-script='#! /bin/bash

		sudo su
		yum -y update
		yum install -y squid 
		yum install httpd-tools -y
		wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/ChefJodlak/GotowanieNaEkranie/master/config.conf --no-check-certificate
		squid -z
		chkconfig squid on
		service squid start
		touch /etc/squid/squid_access; htpasswd -b /etc/squid/squid_access admin admin
		'
	elif [ $c -le 35 ]
	then
		yes | gcloud compute instances create $name$c --machine-type="f1-micro" --image-family=centos-6 --image-project=centos-cloud --tags=http-server,https-server --zone=europe-north1-a --metadata startup-script='#! /bin/bash

		sudo su
		yum -y update
		yum install -y squid 
		yum install httpd-tools -y
		wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/ChefJodlak/GotowanieNaEkranie/master/config.conf --no-check-certificate
		squid -z
		chkconfig squid on
		service squid start
		touch /etc/squid/squid_access; htpasswd -b /etc/squid/squid_access admin admin
		'
	elif [ $c -le 38 ]
	then
		yes | gcloud compute instances create $name$c --machine-type="f1-micro" --image-family=centos-6 --image-project=centos-cloud --tags=http-server,https-server --zone=europe-north1-b --metadata startup-script='#! /bin/bash

		sudo su
		yum -y update
		yum install -y squid 
		yum install httpd-tools -y
		wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/ChefJodlak/GotowanieNaEkranie/master/config.conf --no-check-certificate
		squid -z
		chkconfig squid on
		service squid start
		touch /etc/squid/squid_access; htpasswd -b /etc/squid/squid_access admin admin
		'
	elif [ $c -le 40 ]
	then
		yes | gcloud compute instances create $name$c --machine-type="f1-micro" --image-family=centos-6 --image-project=centos-cloud --tags=http-server,https-server --zone=europe-north1-c --metadata startup-script='#! /bin/bash

		sudo su
		yum -y update
		yum install -y squid 
		yum install httpd-tools -y
		wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/ChefJodlak/GotowanieNaEkranie/master/config.conf --no-check-certificate
		squid -z
		chkconfig squid on
		service squid start
		touch /etc/squid/squid_access; htpasswd -b /etc/squid/squid_access admin admin
		'
	fi
done


